name: Trigger auto deployment for gpu-container

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: [azure-testing]
    paths:
      - "backend/**"
      - "frontend/**"
      - ".github/workflows/gpu-container-AutoDeployTrigger-9a2410cd-d700-45b1-af2d-6a7efeca30f1.yml"

  # Allow manual trigger
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.GPUCONTAINER_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.GPUCONTAINER_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.GPUCONTAINER_AZURE_SUBSCRIPTION_ID }}
          auth-type: 'federated'
          # creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Assign Resource Group Level Permissions
        run: |
          az role assignment create \
            --assignee ${{ secrets.GPUCONTAINER_AZURE_CLIENT_ID }} \
            --role "Contributor" \
            --scope "/subscriptions/${{ secrets.GPUCONTAINER_AZURE_SUBSCRIPTION_ID }}/resourceGroups/summarizer-rg/providers/Microsoft.App/containerApps/gpu-container"

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/backend
          registryUrl: gpuregistry25.azurecr.io
          registryUsername: ${{ secrets.GPUCONTAINER_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.GPUCONTAINER_REGISTRY_PASSWORD }}
          containerAppName: gpu-container
          resourceGroup: summarizer-rg
          imageToBuild: gpuregistry25.azurecr.io/gpu-container:${{ github.sha }}
