name: Deploy to Google Cloud

on:
  push:
    branches: [main]
    paths:
      - "backend/**"
      - "frontend/**"
      - ".github/workflows/gpu-container-AutoDeployTrigger-9a2410cd-d700-45b1-af2d-6a7efeca30f1.yml"

  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          token_format: "access_token"
          create_credentials_file: true

      # Add debug step to verify project configuration
      - name: Debug Project Configuration
        run: |
          echo "Current Project ID: ${{ secrets.GCP_PROJECT_ID }}"
          echo "Listing available projects:"
          gcloud projects list
          echo "Current config:"
          gcloud config list

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          install_components: "docker-credential-gcr"
          
      - name: Verify Secret Manager permissions
        run: |
          # Check if service account has Secret Manager access
          SERVICE_ACCOUNT=$(gcloud config get-value account)
          echo "Using service account: $SERVICE_ACCOUNT"
          gcloud projects add-iam-policy-binding ${{ secrets.GCP_PROJECT_ID }} \
          --member="serviceAccount:$SERVICE_ACCOUNT" \
          --role="roles/secretmanager.secretAccessor"
      # Set up Redis secrets and configuration
      - name: Configure Redis
        run: |
          echo "REDIS_HOST=${{ secrets.REDIS_HOST }}" >> backend/.env
          echo "REDIS_PORT=${{ secrets.REDIS_PORT }}" >> backend/.env
          echo "REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}" >> backend/.env
          echo "REDIS_USERNAME=${{ secrets.REDIS_USERNAME }}" >> backend/.env

      # Add Firebase Admin SDK credentials
      - name: Setup Firebase Credentials
        run: |
          echo '${{ secrets.FIREBASE_ADMIN_SDK_JSON }}' > backend/firebase-adminsdk.json

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker ${{ secrets.GCP_REGION }}-docker.pkg.dev

      - name: Build and Push Backend Container
        run: |
          docker build -t ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/research-assistant/backend:${{ github.sha }} ./backend
          docker push ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/research-assistant/backend:${{ github.sha }}

      - name: Deploy to Cloud Run
        id: deploy-backend
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: research-assistant-backend
          region: ${{ secrets.GCP_REGION }}
          image: ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/research-assistant/backend:${{ github.sha }}
          env_vars: |
            ENVIRONMENT=production
            GCP_PROJECT_ID=${{ secrets.GCP_PROJECT_ID }}
            GCP_PROJECT_NUMBER=${{ secrets.GCP_PROJECT_NUMBER }}
            REDIS_HOST=${{ secrets.REDIS_HOST }}
            REDIS_PORT=${{ secrets.REDIS_PORT }}
            REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}
            REDIS_USERNAME=${{ secrets.REDIS_USERNAME }}
            FIREBASE_PROJECT_ID=${{ secrets.FIREBASE_PROJECT_ID }}
            STRIPE_SECRET_KEY=${{ secrets.STRIPE_SECRET_KEY }}
            STRIPE_WEBHOOK_SECRET=${{ secrets.STRIPE_WEBHOOK_SECRET }}
            STRIPE_PRO_PRICE_ID=${{ secrets.STRIPE_PRO_PRICE_ID }}
            STRIPE_PLUS_PRICE_ID=${{ secrets.STRIPE_PLUS_PRICE_ID }}
          flags: >-
            --port=8000
            --cpu=2
            --memory=4Gi
            --allow-unauthenticated
            --cpu-boost
            --min-instances=1
            --timeout=300

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      # Create frontend environment variables including the backend URL
      - name: Create Frontend Environment
        run: |
          echo "REACT_APP_API_URL=${{ steps.deploy-backend.outputs.url }}" >> frontend/.env
          echo "REACT_APP_FIREBASE_API_KEY=${{ secrets.FIREBASE_API_KEY }}" >> frontend/.env
          echo "REACT_APP_FIREBASE_AUTH_DOMAIN=summarization-3a05c.firebaseapp.com" >> frontend/.env
          echo "REACT_APP_FIREBASE_PROJECT_ID=${{ secrets.FIREBASE_PROJECT_ID }}" >> frontend/.env
          echo "REACT_APP_FIREBASE_APP_ID=${{ secrets.FIREBASE_APP_ID }}" >> frontend/.env

      - name: Build Frontend
        working-directory: ./frontend
        run: |
          npm ci
          npm run build

      # Deploy to Cloud Storage with improved error handling
      - name: Deploy Frontend to Cloud Storage
        run: |
          # Sync build directory to bucket
          gsutil -m rsync -r frontend/build ${{ secrets.GCP_STORAGE_BUCKET }}
          
          # Set cache for HTML files
          gsutil -m setmeta -h "Cache-Control:public, max-age=3600" ${{ secrets.GCP_STORAGE_BUCKET }}/**/*.html || true
          
          # Set cache for CSS and JS files
          for ext in css js; do
            gsutil -m setmeta -h "Cache-Control:public, max-age=31536000" ${{ secrets.GCP_STORAGE_BUCKET }}/**/*.${ext} || true
          done
          
          # Set cache for image files
          for ext in jpg jpeg png gif svg; do
            gsutil -m setmeta -h "Cache-Control:public, max-age=31536000" ${{ secrets.GCP_STORAGE_BUCKET }}/**/*.${ext} || true
          done